version: "3.8"

services:
  auth-service:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - auth-db
    volumes:
      - ./AuthService:/src/AuthService

  app-backend:
    build: ./app-backend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_AUTH_URL=http://auth-service:80
      - DATABASE_URL=postgresql://admin:admin@auth-db:5432/authdb
    depends_on:
      - auth-service
      

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
