services:
  auth-service:
    build:
      context: .
      dockerfile: AuthService/Dockerfile # 🔧 Aponta para o Dockerfile específico do AuthService
    ports:
      - "3000:8080"
    environment:
      - ConnectionStrings__Default=Host=auth-db;Database=authdb;Username=admin;Password=admin
    depends_on:
      - auth-db
    volumes:
      - ./AuthService:/src/AuthService

  app-backend:
    build: ./app-backend
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@app-db:5432/appdb
    depends_on:
      - app-db

  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authdb
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # ⬅️ Opcional: só se quiser acessar o banco fora do container

  app-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appdb
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # ⬅️ Opcional: só se quiser acessar o banco fora do container

volumes:
  auth-db-data:
  app-db-data:
