# Etapa 1: Build da aplicação
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY .env .env

RUN npx prisma generate
RUN npm run build

# Etapa 2: Runtime
FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app ./
COPY .env .env  

EXPOSE 3000
CMD ["npm", "start"]
