FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# 🟢 Instala o cliente PostgreSQL para usar pg_isready
RUN apt-get update && apt-get install -y postgresql-client

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["AuthService/AuthService.csproj", "AuthService/"]
RUN dotnet restore "AuthService/AuthService.csproj"
COPY . .
WORKDIR "/src/AuthService"
RUN dotnet publish "AuthService.csproj" -c Release -o /app/out

FROM base AS final
WORKDIR /app
COPY --from=build /app/out ./

COPY AuthService/entrypoint.sh .
RUN chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]
